# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tech Workers Coalition
email: hello@techworkersco.org
description: A coalition of tech industry workers, labor organizers, community organizers, and friends cultivating solidarity among all workers in tech.
url: "https://techworkerscoalition.org" # the subpath of your site, e.g. /blog
baseurl: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: techworkersco

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-multiple-languages-plugin

jekyll_get_json:
  data: collective-actions
  json: "https://raw.githubusercontent.com/collective-action/tech/master/actions.json"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
languages: ["en", "it", "pt", "ru"]
exclude_from_localizations: ["assets"]
chapters:
  - url: /austin
    text: Austin
  - url: https://twitter.com/twc_bangalore
    text: Bangalore
    newTab: true
  - url: https://techworkersberlin.com/
    text: Berlin
    newTab: true
  - url: https://boston.techworkerscoalition.org/
    text: Boston
  - url: /chicago
    text: Chicago
  - url: /dc
    text: DC
  - url: https://www.meetup.com/Tech-Workers-Coalition-LA
    text: LA
    newTab: true
  - url: /london
    text: London
  - url: /nyc
    text: NYC
  - url: /pdx
    text: PDX
  - url: https://www.meetup.com/TWCSanDiego
    text: San Diego
    newTab: true
  - url: /seattle
    text: Seattle
  - url: /sf-bay-area
    text: SF Bay Area
links:
  - url: /subscribe
    text: Join the Slack
  - url: /community-guide/
    text: Community Guide
  - url: https://news.techworkerscoalition.org/subscribe/
    text: Newsletter
  - url: https://sites.google.com/view/tech-workers-coalition/learning-club
    text: Learning Clubs
    newTab: true
  - url: https://medium.com/tech-workers-coalition
    text: Medium
    newTab: true
  - url: https://twitter.com/techworkersco
    text: Twitter
    newTab: true
  - url: https://www.facebook.com/TechWorkersCoalition
    text: Facebook
    newTab: true
sass:
  style: compressed

port: 8080
